### ISSUE TITLE
deploy-local failing

### ISSUE THREAD

**Issue by enterJazz** [TUM-DSE/doctor-cluster-config#370]
Currently, on:
- vislor
- ryan
- christina
`inv deploy-local` is failing due to `nvd`:
```
$ inv deploy-local
warning: ignoring untrusted flake configuration setting 'extra-substituters'.
Pass '--accept-flake-config' to trust it
warning: ignoring untrusted flake configuration setting 'extra-trusted-public-keys'.
Pass '--accept-flake-config' to trust it
building the system configuration...
warning: ignoring untrusted flake configuration setting 'extra-substituters'.
Pass '--accept-flake-config' to trust it
warning: ignoring untrusted flake configuration setting 'extra-trusted-public-keys'.
Pass '--accept-flake-config' to trust it
activating the configuration...
--- diff to current-system
Traceback (most recent call last):
  File "/nix/store/dqv9i2b69i8g2cgjxyyw6qs4c0qa4f5s-nvd-0.2.0/bin/nvd", line 757, in <module>
<<< /run/current-system
>>> /nix/store/p5x798h24bx1faszm1a411g0kv1wni1w-nixos-system-christina-23.05.20230925.58b09ee
    main()
  File "/nix/store/dqv9i2b69i8g2cgjxyyw6qs4c0qa4f5s-nvd-0.2.0/bin/nvd", line 749, in main
    {
  File "/nix/store/dqv9i2b69i8g2cgjxyyw6qs4c0qa4f5s-nvd-0.2.0/bin/nvd", line 556, in run_diff
    left_manifest = PackageManifest.parse_tree((left_resolved / "sw").resolve())
  File "/nix/store/dqv9i2b69i8g2cgjxyyw6qs4c0qa4f5s-nvd-0.2.0/bin/nvd", line 232, in parse_tree
    direct_deps: List[str] = subprocess.run(
  File "/nix/store/bc45k1n0pkrdkr3xa6w84w1xhkl1kkyp-python3-3.10.12/lib/python3.10/subprocess.py", line 503, in run
    with Popen(*popenargs, **kwargs) as process:
  File "/nix/store/bc45k1n0pkrdkr3xa6w84w1xhkl1kkyp-python3-3.10.12/lib/python3.10/subprocess.py", line 971, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/nix/store/bc45k1n0pkrdkr3xa6w84w1xhkl1kkyp-python3-3.10.12/lib/python3.10/subprocess.py", line 1863, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'nix-store'
---
Activation script snippet 'diff' failed (1)
sops-install-secrets: Imported /etc/ssh/ssh_host_rsa_key as GPG key with fingerprint 51437f8acce4e97b1788a99e261839b635338e53
sops-install-secrets: Imported /etc/ssh/ssh_host_ed25519_key as age key with fingerprint age168tqvf7373e7wj0q8p0trzm5t0mvlp4t296uuswa98s2waerfsgqdvzmhe
setting up /etc...
sops-install-secrets: Imported /etc/ssh/ssh_host_rsa_key as GPG key with fingerprint 51437f8acce4e97b1788a99e261839b635338e53
sops-install-secrets: Imported /etc/ssh/ssh_host_ed25519_key as age key with fingerprint age168tqvf7373e7wj0q8p0trzm5t0mvlp4t296uuswa98s2waerfsgqdvzmhe
reloading user units for okelmann...
reloading user units for robert...
setting up tmpfiles
warning: error(s) occurred while switching to the new configuration
```

i am currently trying to debug this, however if anybody saw this before, please let me know

**Comment by Mic92** [comment]
This was fixed in https://github.com/numtide/srvos/commit/824a58d7af3e233255a1309e5ebe50eb2ca32d17
